import './bootstrap';
import { createApp } from 'vue';
import { createRouter, createWebHistory } from 'vue-router';
import router from "./routes/index";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap';
import ToastPlugin from 'vue-toast-notification';
import 'vue-toast-notification/dist/theme-bootstrap.css';
import App from './components/utilities/App.vue';
const app = createApp(App);
import { pinia } from './store';
app.use(pinia);
app.use(router);
app.use(ToastPlugin);
app.mount('#app');